### PR TITLE
Fork wslay and change submodule URI

### LINKED ISSUE #14: Fork wslay and change submodule URI
Our usual policy for submodules is to fork an upstream repository into tarantool organization and use the fork in the submodule URI. The main reason is to protect ourself from destructive upstream actions: removal, renaming, change of source code hosting / VCS, force-pushing. The side reason is to be able to implement our own functionality and use it before it'll be released in the upstream.

Now wslay is enabled directly:

https://github.com/tarantool/httpng/blob/ffef68a602aec597c45792a6380ccd9793773bfb/.gitmodules#L10-L12

Let's also consider sticking to a release version, now we use the latest wslay's `master`.

### PR DESCRIPTION
**Pull request by artemreyt**
Changed URL of wslay to tarantool fork repo.

Closes #14

### CODE REVIEW

**Comment by Totktonada** [comment]
Moving back from current wslay master to the latest release looks a bit risky (however it builds and seems to work for me). I mean, a bit more risky than leaving it as is for now (at least I see some extra checks and fixes for clang-10). I would just update to the next release, when wslay will be released next time.

**Comment by artemreyt** [comment]
>  I would just update to the next release, when wslay will be released next time.

Ok, agree. Left master.

**Comment by Totktonada** [comment]
I got the following error on current master (3d726d8526a3c6e1452b57a9c7fd063e8ca8eda4):

> [ 31%] Linking CXX shared library httpng.so
> /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: third_party/wslay/lib/libwslay.a(wslay_event.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
> /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: third_party/wslay/lib/libwslay.a(wslay_queue.c.o): warning: relocation in read-only section `.text'
> clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [CMakeFiles/httpng.dir/build.make:109: httpng.so] Error 1
> make[1]: *** [CMakeFiles/Makefile2:235: CMakeFiles/httpng.dir/all] Error 2
> make: *** [Makefile:149: all] Error 2

(I removed the problematic static assert in our code to check the build.)

The command:

> CC=clang-10 CXX=clang++-10 cmake . && make -j

It is on Linux.

Just for information.

**Comment by artemreyt** [comment]
> I got the following error on current master ([3d726d8](https://github.com/tarantool/httpng/commit/3d726d8526a3c6e1452b57a9c7fd063e8ca8eda4)):
> 
> > [ 31%] Linking CXX shared library httpng.so
> > /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: third_party/wslay/lib/libwslay.a(wslay_event.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: third_party/wslay/lib/libwslay.a(wslay_queue.c.o): warning: relocation in read-only section `.text'
> > clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
> > make[2]: *** [CMakeFiles/httpng.dir/build.make:109: httpng.so] Error 1
> > make[1]: *** [CMakeFiles/Makefile2:235: CMakeFiles/httpng.dir/all] Error 2
> > make: *** [Makefile:149: all] Error 2
> 
> (I removed the problematic static assert in our code to check the build.)
> 
> The command:
> 
> > CC=clang-10 CXX=clang++-10 cmake . && make -j
> 
> It is on Linux.
> 
> Just for information.

Did error occurred after getting back to wslay master? Or it isn't related to this issue?

**Comment by Totktonada** [comment]
Ouch, my master was a bit outdated. Re-tested on 13cd583cdc4843af6733db38169a59c44d847e8b, but the result is the same.

**Comment by Totktonada** [comment]
> Did error occurred after getting back to wslay master? Or it isn't related to this issue?

It is irrelevant and occurs with wslay master and release-1.1.1 both.

**Review by Totktonada — APPROVED** [review]
LGTM.

**Comment by Totktonada** [comment]
Extra manual steps are necessary to apply this change on existing repository (after `git pull`):

```sh
$ vim .git/config
<go to [submodule "third_party/wslay"]>
<change url to https://github.com/tarantool/wslay.git>
$ cd third_party/wslay/
$ git remote remove origin
$ git remote add origin https://github.com/tarantool/wslay.git
```

Without those steps the submodule will actually look into the upstream repository.

**Comment by artemreyt** [comment]
> Extra manual steps are necessary to apply this change on existing repository (after `git pull`):
> 
> ```shell
> $ vim .git/config
> <go to [submodule "third_party/wslay"]>
> <change url to https://github.com/tarantool/wslay.git>
> $ cd third_party/wslay/
> $ git remote remove origin
> $ git remote add origin https://github.com/tarantool/wslay.git
> ```
> 
> Without those steps the submodule will actually look into the upstream repository.

For such cases there is `git submodule sync`.
You just can do `git submodule sync --recursive` to synchronize  URL of remote repositories set in `.gitmodules`  with remotes in submodules and change remotes in `.git/config`.

**Pull request merged**
