### PR TITLE
add force_decrease_threads() api

### PR DESCRIPTION
**Pull request by void234**
Part of #18

### CODE REVIEW

**Comment by Totktonada** [comment]
What may prevent a thread from being terminated gracefully? Are we obligated to terminate it before returning from `httpng.cfg()` or can do this in background?

I also think that it should be controlled by `httpng.cfg()` rather than via a separate function. So my (quite blind, because I don't know many details) proposal is to replace `httpng.force_descrease_threads()` with `httpng.cfg({thread_termination_timeout = <...>})` and perform the thread termination in background.

I briefly discussed it with @Mons and we agreed on the API of this kind (however, sure, we need your knowledge about the implementation to decide).

----

General note: It would be good to engage @Mons into a discussion about a new API prior to publishing it in master (please, keep in the mind that `tarantoolctl rocks install httpng` installs a latest master).

**Comment by void234** [comment]
> What may prevent a thread from being terminated gracefully?

A user downloading a large file via a slow connection for example. I have an example in tests/all.lua - g_hot_reload_with_curls.test_FLAKY_decrease_stubborn_threads(), handler sends data in a infinite loop and curl eats it all.

> Are we obligated to terminate it before returning from `httpng.cfg()` or can do this in background?

This is being done in the background - "decreased" threads do not receive new connections and disable HTTP/1.x keep-alive (but not similar feature for HTTP/2, at least yet). Once there are no requests, the thread exits (some new requests through existing TCP connections can fail at this stage - but I see no way around that, we have to close TCP connections at some point). Some resources, however, are freed only on the next call to cfg()/shutdown() etc.

> I also think that it should be controlled by `httpng.cfg()` rather than via a separate function. So my (quite blind, because I don't know many details) proposal is to replace `httpng.force_descrease_threads()` with `httpng.cfg({thread_termination_timeout = <...>})` and perform the thread termination in background.

As you wish. I, however, intend to keep force_decrease_threads() because it is more convenient to use when we have set too large timeout and want to speed things up.

> I briefly discussed it with @Mons and we agreed on the API of this kind (however, sure, we need your knowledge about the implementation to decide).

While we are at it, should we do the same for shutdown()? Right now it is ungraceful. Should we make it graceful with some default timeout if thread_termination_timeout is not specified? @Mons?

> General note: It would be good to engage @Mons into a discussion about a new API prior to publishing it in master (please, keep in the mind that `tarantoolctl rocks install httpng` installs a latest master).

This is exactly why I have not implemented timeout yet.

**Comment by Totktonada** [comment]
I would provide a default timeout (or two: per thread and overall) and ability to configure it. Don't know how to better name the overall thread termination timeout.

Regarding forceful termination: why not via `httpng.cfg({thread_termination_timeout = <...>})`?

I think it worth to pass a review process for all public API changes (including additions). Aside, maybe, some `httpng._internal` namespace. If @Mons agree to keep its responsibility for the public API of the module.

**Comment by void234** [comment]
> I would provide a default timeout (or two: per thread and overall)

What do you mean by "overall"? All threads start shutting down [almost] at the same time. Separate timeouts for "decrease threads" and "shutdown"?

> and ability to configure it.

Where exactly should it be configured? Some global variable?

> Don't know how to better name the overall thread termination timeout.
> 
> Regarding forceful termination: why not via `httpng.cfg({thread_termination_timeout = <...>})`?

Do you mean ```httpng.shutdown({thread_termination_timeout = <...>})```? `.cfg()` performs start or hot reload.

I mean:
Should shutdown() remain ungraceful?
Should "0" timeout mean "ungraceful"?
Should "-1" / "any negative value" mean "unlimited timeout"? [damn Lua doubles BTW]
What should be the default (when `thread_termination_timeout == nil`)?

```httpng.cfg({thread_termination_timeout = <...>})``` approach has one obvious problem: for reconfiguration you should add that item into the table you pass to httpng.cfg() (first call may not had `thread_termination_timeout`). Should I save it for future calls to `cfg()`/`shutdown()`? What if there is no such item in the next call to `cfg()`? `shutdown()`?
The way I see it (and use it in my tests): a user creates a table and passes it to `cfg()`. Then he modifies this table and calls `cfg()` again. It is easy to add `thread_termination_timeout` with some value and forget about it. Then `shutdown()` would do something unexpected. BTW, should `shutdown()` return immediately if the graceful shutdown is requested? If not - what if timeout is several hours?

We definitely need @Mons here ;-)

> I think it worth to pass a review process for all public API changes (including additions). Aside, maybe, some `httpng._internal` namespace. If @Mons agree to keep its responsibility for the public API of the module.

I hate leading underscores. I have seen three and even four of them in single function name in real code. Even in Linux.
But I would think about adding auxiliary functions (testing/debugging etc) into some embedded table.

**Comment by Totktonada** [comment]
> What do you mean by "overall"? All threads start shutting down [almost] at the same time. Separate timeouts for "decrease threads" and "shutdown"?

Ouch, sure, they're truthly parallel. Please, disregard.

> Where exactly should it be configured? Some global variable?

In my understanding all configuration should be performed by `httpng.cfg()`.

> > Regarding forceful termination: why not via `httpng.cfg({thread_termination_timeout = <...>})`?
> 
> Do you mean `httpng.shutdown({thread_termination_timeout = <...>})`? `.cfg()` performs start or hot reload.

I meant `httpng.cfg({thread_termination_timeout = <...>})` before `httpng.shutdown()`.

> I mean:
> Should shutdown() remain ungraceful?

It should depend on the current configuration (the configured timeout).

> Should "0" timeout mean "ungraceful"?

I guess so.

> Should "-1" / "any negative value" mean "unlimited timeout"? [damn Lua doubles BTW]

I don't see such approach over tarantool API (box.cfg() timeouts, net.box, socket), so I would provide a module level constant TIMEOUT_INFINITY (say, `500 * 365 * 86400`) instead.

> What should be the default (when `thread_termination_timeout == nil`)?

Correction: when `httpng.cfg({thread_termination_timeout = box.NULL})`, `nil` is no-value in a table. It is how a value is unset for `box.cfg(<...>)`. See details below.

I think that the default value should NOT be infinity, but rather something large enough to be usually successful and low enough to be okay during application (re)initialization. Considering typical RTT in the internet as 100ms or lower, I would choose 1 second.

> `httpng.cfg({thread_termination_timeout = <...>})` approach has one obvious problem: for reconfiguration you should add that item into the table you pass to httpng.cfg() (first call may not had `thread_termination_timeout`). Should I save it for future calls to `cfg()`/`shutdown()`? What if there is no such item in the next call to `cfg()`? `shutdown()`?
> The way I see it (and use it in my tests): a user creates a table and passes it to `cfg()`. Then he modifies this table and calls `cfg()` again. It is easy to add `thread_termination_timeout` with some value and forget about it. Then `shutdown()` would do something unexpected. BTW, should `shutdown()` return immediately if the graceful shutdown is requested? If not - what if timeout is several hours?

I think that `box.cfg({<...>})` way is convenient and solves most of problems. It remembers previous values, so if you need to adjust just one option (say, `replication_timeout`), you can pass just the option: `box.cfg({replication_timeout = 10})`. Pass `box.NULL` to drop the value to the default one. It does not matter, whether the passed table is the same or another one: let's consider the table here as a way to pass named arguments.

I hope this approach will solve most of usability problems.

> BTW, should `shutdown()` return immediately if the graceful shutdown is requested? If not - what if timeout is several hours?

I would wait till end of .cfg() / .shutdown() action. If a user really want to do it in background, it can spawn a fiber for that (just like with `box.cfg()`).

If a user requested several hours timeout, than I hope (s)he knows what (s)he are doing.

> > I think it worth to pass a review process for all public API changes (including additions). Aside, maybe, some `httpng._internal` namespace. If @Mons agree to keep its responsibility for the public API of the module.
> 
> I hate leading underscores. I have seen three and even four of them in single function name in real code. Even in Linux.
> But I would think about adding auxiliary functions (testing/debugging etc) into some embedded table.

Just one is enough here. The nice thing here is that fields with leading underscore are excluded from tab completion (except when the undescore is already typed). So a user will not see them, when experimenting in the interactive console.

**Comment by void234** [comment]
> > Where exactly should it be configured? Some global variable?
> 
> In my understanding all configuration should be performed by `httpng.cfg()`.
> 
> > > Regarding forceful termination: why not via `httpng.cfg({thread_termination_timeout = <...>})`?
> > 
> > 
> > Do you mean `httpng.shutdown({thread_termination_timeout = <...>})`? `.cfg()` performs start or hot reload.
> 
> I meant `httpng.cfg({thread_termination_timeout = <...>})` before `httpng.shutdown()`.

There are several problems with this approach, please see below.
 
> > I mean:
> > Should shutdown() remain ungraceful?
> 
> It should depend on the current configuration (the configured timeout).

First of all, I believe that [defaut] shutdown timeout should be way different from "thread decrease" timeout. In the first case the server is shutting down (probably to be restarted with different settings) and we have some downtime, so it shutdown() should return quickly for us to begin reconfiguration. A timeout of a few seconds seems appropriate. In the second case we are probably tuning server performance (giving CPU cores to something else), a minimal number of existing TCP connections are affected and we probably do not need a sharp CPU usage drop to 0% on affected CPU cores (even if would use thread affinity eventually). A timeout of a few minutes or even hours seems appropriate.
 
> > Should "0" timeout mean "ungraceful"?
> 
> I guess so.
> 
> > Should "-1" / "any negative value" mean "unlimited timeout"? [damn Lua doubles BTW]
> 
> I don't see such approach over tarantool API (box.cfg() timeouts, net.box, socket), so I would provide a module level constant TIMEOUT_INFINITY (say, `500 * 365 * 86400`) instead.

Should we check for `== TIMEOUT_INFINITY` or ">= TIMEOUT_INFINITY`? BTW 500 years is not long enough ;-)
"math.huge"? Books about Lua prefer that.

> > What should be the default (when `thread_termination_timeout == nil`)?
> 
> Correction: when `httpng.cfg({thread_termination_timeout = box.NULL})`, `nil` is no-value in a table. It is how a value is unset for `box.cfg(<...>)`. See details below.
> 
> I think that the default value should NOT be infinity, but rather something large enough to be usually successful and low enough to be okay during application (re)initialization. Considering typical RTT in the internet as 100ms or lower, I would choose 1 second.
> 
> > `httpng.cfg({thread_termination_timeout = <...>})` approach has one obvious problem: for reconfiguration you should add that item into the table you pass to httpng.cfg() (first call may not had `thread_termination_timeout`). Should I save it for future calls to `cfg()`/`shutdown()`? What if there is no such item in the next call to `cfg()`? `shutdown()`?
> > The way I see it (and use it in my tests): a user creates a table and passes it to `cfg()`. Then he modifies this table and calls `cfg()` again. It is easy to add `thread_termination_timeout` with some value and forget about it. Then `shutdown()` would do something unexpected. BTW, should `shutdown()` return immediately if the graceful shutdown is requested? If not - what if timeout is several hours?
> 
> I think that `box.cfg({<...>})` way is convenient and solves most of problems. It remembers previous values, so if you need to adjust just one option (say, `replication_timeout`), you can pass just the option: `box.cfg({replication_timeout = 10})`. Pass `box.NULL` to drop the value to the default one. It does not matter, whether the passed table is the same or another one: let's consider the table here as a way to pass named arguments.

Right now the approach is different but this is not the main problem. `httpng.cfg()` can be passed table of "sites" (sets of paths and handlers). How do you propose to remove items from that table? `httpng.cfg { sites = { .path = '/something', handler = box.NULL } }`?
And so far httpng didn't depend on "box" at all.

> I hope this approach will solve most of usability problems.
> 
> > BTW, should `shutdown()` return immediately if the graceful shutdown is requested? If not - what if timeout is several hours?
> 
> I would wait till end of .cfg() / .shutdown() action. If a user really want to do it in background, it can spawn a fiber for that (just like with `box.cfg()`).

So sysadmin must remember timeout value which was configured [by a previous sysadmin] e. g. several months before. I do not like that.
Should we at least print some warning?
> 
> If a user requested several hours timeout, than I hope (s)he knows what (s)he are doing.
False hope.

**Comment by Totktonada** [comment]
> > > I mean:
> > > Should shutdown() remain ungraceful?
> > 
> > 
> > It should depend on the current configuration (the configured timeout).
> 
> First of all, I believe that [defaut] shutdown timeout should be way different from "thread decrease" timeout. In the first case the server is shutting down (probably to be restarted with different settings) and we have some downtime, so it shutdown() should return quickly for us to begin reconfiguration. A timeout of a few seconds seems appropriate. In the second case we are probably tuning server performance (giving CPU cores to something else), a minimal number of existing TCP connections are affected and we probably do not need a sharp CPU usage drop to 0% on affected CPU cores (even if would use thread affinity eventually). A timeout of a few minutes or even hours seems appropriate.

Hm. Okay, if cases are different, it seems meaningful to add `thread_termination_timeout` option into `httpng.shutdown()`: `httpng.shutdown({thread_termination_timeout = <...>})` (and lean on the configured timeout otherwise). Passing this option to the shutdown function should not change the configured value.

> > > Should "-1" / "any negative value" mean "unlimited timeout"? [damn Lua doubles BTW]
> > 
> > 
> > I don't see such approach over tarantool API (box.cfg() timeouts, net.box, socket), so I would provide a module level constant TIMEOUT_INFINITY (say, `500 * 365 * 86400`) instead.
> 
> Should we check for `== TIMEOUT_INFINITY` or ">= TIMEOUT_INFINITY`? BTW 500 years is not long enough ;-)
> "math.huge"? Books about Lua prefer that.

500 years looks enough. No one complains yet (we have 100 or 500 years as TIMEOUT_INFINITY across tarantool code base).

I don't think we should check a timeout value for equality (or lower / bigger) with `TIMEOUT_INFINITY`: just use the timeout as the usual one.

> > I think that `box.cfg({<...>})` way is convenient and solves most of problems. It remembers previous values, so if you need to adjust just one option (say, `replication_timeout`), you can pass just the option: `box.cfg({replication_timeout = 10})`. Pass `box.NULL` to drop the value to the default one. It does not matter, whether the passed table is the same or another one: let's consider the table here as a way to pass named arguments.
> 
> Right now the approach is different but this is not the main problem. `httpng.cfg()` can be passed table of "sites" (sets of paths and handlers). How do you propose to remove items from that table? `httpng.cfg { sites = { .path = '/something', handler = box.NULL } }`?
>
> And so far httpng didn't depend on "box" at all.

We should follow `box.cfg({<...>})` way, where applicable: it is what every tarantool user expects from a `.cfg()` function.

Regarding "sites": the rough analogue is how `box.cfg({replication =  <...>})` works: it replaces the old upstreams list with the new one. So, the configuration is incremental (diff-like) only on the top level.

We can introduce some way to register and unregister "sites" in an incremental way, say, `httpng.cfg({add_sites = <...>})`. However it just raw idea: I don't know, whether there is a need and how exactly the API should look.

> > > BTW, should `shutdown()` return immediately if the graceful shutdown is requested? If not - what if timeout is several hours?
> >
> > I would wait till end of .cfg() / .shutdown() action. If a user really want to do it in background, it can spawn a fiber for that (just like with `box.cfg()`).
> 
> So sysadmin must remember timeout value which was configured [by a previous sysadmin] e. g. several months before. I do not like that.

Just print `httpng.cfg.thread_termination_timeout` before doing shutdown?

> Should we at least print some warning?

I don't mind.

**Comment by void234** [comment]
> > > > I mean:
> > > > Should shutdown() remain ungraceful?
> > > 
> > > 
> > > It should depend on the current configuration (the configured timeout).
> > 
> > 
> > First of all, I believe that [defaut] shutdown timeout should be way different from "thread decrease" timeout. In the first case the server is shutting down (probably to be restarted with different settings) and we have some downtime, so it shutdown() should return quickly for us to begin reconfiguration. A timeout of a few seconds seems appropriate. In the second case we are probably tuning server performance (giving CPU cores to something else), a minimal number of existing TCP connections are affected and we probably do not need a sharp CPU usage drop to 0% on affected CPU cores (even if would use thread affinity eventually). A timeout of a few minutes or even hours seems appropriate.
> 
> Hm. Okay, if cases are different, it seems meaningful to add `thread_termination_timeout` option into `httpng.shutdown()`: `httpng.shutdown({thread_termination_timeout = <...>})` (and lean on the configured timeout otherwise). Passing this option to the shutdown function should not change the configured value.

I believe that it should be a separate option like "shutdown_timeout" with different timeout. This way it could be specified as a parameter for "original" `cfg()`.

> 
> > > I think that `box.cfg({<...>})` way is convenient and solves most of problems. It remembers previous values, so if you need to adjust just one option (say, `replication_timeout`), you can pass just the option: `box.cfg({replication_timeout = 10})`. Pass `box.NULL` to drop the value to the default one. It does not matter, whether the passed table is the same or another one: let's consider the table here as a way to pass named arguments.
> > 
> > 
> > Right now the approach is different but this is not the main problem. `httpng.cfg()` can be passed table of "sites" (sets of paths and handlers). How do you propose to remove items from that table? `httpng.cfg { sites = { .path = '/something', handler = box.NULL } }`?
> > And so far httpng didn't depend on "box" at all.
> 
> We should follow `box.cfg({<...>})` way, where applicable: it is what every tarantool user expects from a `.cfg()` function.
> 
> Regarding "sites": the rough analogue is how `box.cfg({replication = <...>})` works: it replaces the old upstreams list with the new one. So, the configuration is incremental (diff-like) only on the top level.

There is one problem with this approach: in addition to `sites = { {path = '/' , handler = foo } }` (we need `sites` at least for "native" h2o file hosting, planned for Q2) we also have "global" `cfg.handler` (with implicit `path= '/'`). Inconsistent.

> We can introduce some way to register and unregister "sites" in an incremental way, say, `httpng.cfg({add_sites = <...>})`. However it just raw idea: I don't know, whether there is a need and how exactly the API should look.

Ok, I would probably implement something like this.

> > > > BTW, should `shutdown()` return immediately if the graceful shutdown is requested? If not - what if timeout is several hours?
> > > 
> > > 
> > > I would wait till end of .cfg() / .shutdown() action. If a user really want to do it in background, it can spawn a fiber for that (just like with `box.cfg()`).
> > 
> > 
> > So sysadmin must remember timeout value which was configured [by a previous sysadmin] e. g. several months before. I do not like that.
> 
> Just print `httpng.cfg.thread_termination_timeout` before doing shutdown?

Yes, but "shutdown_timeout".
 
> > Should we at least print some warning?
> 
> I don't mind.

**Comment by Totktonada** [comment]
> I believe that it should be a separate option like "shutdown_timeout" with different timeout. This way it could be specified as a parameter for "original" `cfg()`.

I'm in doubts that it'll look simpler from a user perspective. I think it worth to do attempt to describe your variant in a documentation and look, whether it'll look clear enough.

> There is one problem with this approach: in addition to `sites = { {path = '/' , handler = foo } }` (we need `sites` at least for "native" h2o file hosting, planned for Q2) we also have "global" `cfg.handler` (with implicit `path= '/'`). Inconsistent.

So, there are two ways to set `path = '/'` route (but one of them conflicts with presence of another routes). Any way to set the `path = '/'` route should set it if there are no conflicts in the resulting configuration. Looks meaningful?

**Comment by void234** [comment]
> > I believe that it should be a separate option like "shutdown_timeout" with different timeout. This way it could be specified as a parameter for "original" `cfg()`.
> 
> I'm in doubts that it'll look simpler from a user perspective. I think it worth to do attempt to describe your variant in a documentation and look, whether it'll look clear enough.

Ok, I'll do that.

> > There is one problem with this approach: in addition to `sites = { {path = '/' , handler = foo } }` (we need `sites` at least for "native" h2o file hosting, planned for Q2) we also have "global" `cfg.handler` (with implicit `path= '/'`). Inconsistent.
> 
> So, there are two ways to set `path = '/'` route (but one of them conflicts with presence of another routes). Any way to set the `path = '/'` route should set it if there are no conflicts in the resulting configuration. Looks meaningful?

Adding paths/changing handlers is not a problem, removing is.

`httpg.cfg( { sites = { { path = '/', handler = foo } } } )` - We have a handler for '/'.
`httpg.cfg( { handler = box.NULL } )` - We are removing handler for '/'.

`httpg.cfg( { handler = foo } )` - We have a handler for '/'.
`httpg.cfg( { remove_sites = { { path = '/' } } } )` - We are removing handler for '/'.

Is this ok?

**Comment by Totktonada** [comment]
Is `handler = function() <...> end` handles all requests, not just `/`?

**Comment by void234** [comment]
> Is `handler = function() <...> end` handles all requests, not just `/`?

Just '/'.
But the handler for '/' handles everything which has no specific `path` so it must be the last entry in `sites` (this is checked in httpng). I just feed libh2o.

**Comment by Totktonada** [comment]
Is it specific for the `/` handler or all paths are interpreted as a prefix, suffix, substring, regex? Please, explain. That's surprising behaviour.

'Just feed libh2o' does not explain me anything, sorry.

**Comment by void234** [comment]
> Is it specific for the `/` handler or all paths are interpreted as a prefix, suffix, substring, regex? Please, explain. That's surprising behaviour.

Prefix, as far as I can tell - didn't investigate that in detail yet. There is nothing specific about "/", it just can optionally be specified w/o using "sites" at Mons's request.
There is no "router" in httpng yet, that's #3 (Q2) + #4 (Q2), #37 (Q3)
It also depends on "virtual hosts"/SNI so I am waiting for multilisten merge to implement that properly.

**Comment by Totktonada** [comment]
So, back to our discussion.

The `handler` option conflicts with `sites`. So, if existing configuration contains `sites`, `httpng.cfg{handler = function(<...>) <...> end}` should raise an error. Correct variant: `httpng.cfg{handler = function(<...>) <...> end, sites = box.NULL}`. And vice versa: if `handler` is set in the existing configuration, it should be removed (using `box.NULL`) explicitly at reconfiguration to set `sites`.

Looks meaningful?

**Comment by void234** [comment]
> So, back to our discussion.
> 
> The `handler` option conflicts with `sites`. So, if existing configuration contains `sites`, `httpng.cfg{handler = function(<...>) <...> end}` should raise an error.

Why?
There could be paths apart from '/' (that is what `sites` is for).
Even if there is a `sites` record with `path == '/'`, I see no problem in replacing a handler for '/'.

> Correct variant: `httpng.cfg{handler = function(<...>) <...> end, sites = box.NULL}`.

What about "other" `path`s? Remove everything? Remove only '/' and do not touch others?

> And vice versa: if `handler` is set in the existing configuration, it should be removed (using `box.NULL`) explicitly at reconfiguration to set `sites`.
> 
> Looks meaningful?

I definitely do not like that approach.

**Comment by Totktonada** [comment]
> Why?

I found it confusing to implicitly roll back configured option, when another, conflicting one, is passed.

> What about "other" `path`s? Remove everything? Remove only '/' and do not touch others?

`/` prefix means 'all', so, yep, any `handler` function conflicts with any non-empty list of `sites`.

**Comment by void234** [comment]
> > Why?
> 
> I found it confusing to implicitly roll back configured option, when another, conflicting one, is passed.

Using both `sites` with `path == '/'` and `handler` is atypical, users would probably use a single approach. What you are proposing makes thing confusing for everyone.

> > What about "other" `path`s? Remove everything? Remove only '/' and do not touch others?
> 
> `/` prefix means 'all', so, yep, any `handler` function conflicts with any non-empty list of `sites`.

`httpng.cfg( { sites = { { path = '/foo', handler = foo } } } )`
`httpng.cfg( handler = bar )`
Why this code should fail?

`httpng.cfg( { sites = { { path = '/foo', handler = foo } } } )`
`httpng.cfg( { add_sites = { { path = '/', handler = bar } } } )`
This code would still work.

These two pieces of code above do the same thing. There is a handler for '/foo' and a handler for '/'.

`httpng.cfg( handler = bar )`
`httpng.cfg( { sites = { { path = '/foo', handler = foo } } } )`
Should this code fail?

`httpng.cfg( handler = bar )`
`httpng.cfg( { sites = { { path = '/', handler = another_bar } } } )`
What about this one? It does the same thing as 

`httpng.cfg( { sites = { { path = '/', handler = bar } } } )`
`httpng.cfg( { sites = { { path = '/', handler = another_bar } } } )`

or

`httpng.cfg( { handler = bar } )`
`httpng.cfg( { handler = another_bar } )`

**Comment by void234** [comment]
You have no problem with
`httpng.cfg( { sites = { { path = '/bar', handler = bar } } } )`
`httpng.cfg( { sites = { { path = '/bar', handler = another_bar } } } )`
Right?

**Comment by Totktonada** [comment]
I'll repeat: `/` prefix means 'all'. Including `/foo`.

I'm not sure that it is what a user expects. It was surprise for me that you decided to configure paths as path prefixes. So, maybe, we should revisit it first. All comments regarding correct way to configure an instance are made in the guess that we'll keep this way. I cannot guarantee it, though.

**Comment by void234** [comment]
> I'll repeat: `/` prefix means 'all'. Including `/foo`.

Then there is no point in `sites` at all and we can't implement #38 (which is in Q2). Not even with separate "virtual host" for file hosting because @Mons have cut up "virtual host" support already.

Maybe you intended to write "`httpng.cfg{ handler = ...}` means 'all'. Including `/foo`."?
 
> I'm not sure that it is what a user expects. It was surprise for me that you decided to configure paths as path prefixes.

I just exposed libh2o internals, like it was originally planned. `httpng.cfg{ handler = ...}` was added later.

> So, maybe, we should revisit it first. All comments regarding correct way to configure an instance are made in the guess that we'll keep this way. I cannot guarantee it, though.

@Mons?

**Comment by Totktonada** [comment]
> Maybe you intended to write "`httpng.cfg{ handler = ...}` means 'all'. Including /foo."?

I lean on your description of the current API in https://github.com/tarantool/httpng/pull/127#issuecomment-847641641. AFAIU, any path is a prefix in fact disregarding whether it is assumed by `handler` or is set in `sites` (I also guess that 'prefix' means the following: `path = /foo` will catch `GET /foo/bar HTTP/1.1`, but not `GET /foobar HTTP/1.1`).

I meant exacly what I wrote, but, yep, in particular, `handler` presence means processing of all routes (including /foo) by this handler.

Anyway, I see that it is hard to discuss anything without an API description. I propose to describe how things are implemented now (#140) to have a solid ground under feets and return here back.

----

I had a brief discussion with @Mons regarding all those points. The summary is below.

1. There were no `sites` in his API proposal. Instead, there is a separate router (#4), which is configured separately and attached into `httpng.cfg{handler = <...>}`. The API of the router is to be discussed.
2. It seems, we barely unable to discuss the API of the module, because nobody knows current API (sorry, but that's so). The priority of #140 is very high so. I moved it to Q2. It is more valuable than, say, static file serving. After #140 all changes that relevant to the API must update the API documentation.
3. If you have thoughts or a proposal about static file serving API, please, share it.

From me: We should agree how to discuss the API before it'll appear in `master`. Current process ('just push it') was okay for first several months of development, but I hope we'll finish this early stage of development soon and we'll have first early adopters soon.

I can propose several options:

1. Discuss API in the relevant issues.
2. Enable discussions for this repository and raise questions there.
3. Review API in a PR together with an implementation (those PRs will require a review so; the downside here is possibility that the implementation should be rewritten after the API discussion, so I don't recommend this way).

Any option is okay for me. Please, choose one or propose another way.

**Comment by void234** [comment]
> 
> 
> > Maybe you intended to write "`httpng.cfg{ handler = ...}` means 'all'. Including /foo."?
> 
> I lean on your description of the current API in [#127 (comment)](https://github.com/tarantool/httpng/pull/127#issuecomment-847641641). AFAIU, any path is a prefix in fact disregarding whether it is assumed by `handler` or is set in `sites`

Yes, libh2o requires at least one `path` to work ('/foo' or '/' or whatever).

> (I also guess that 'prefix' means the following: `path = /foo` will catch `GET /foo/bar HTTP/1.1`, but not `GET /foobar HTTP/1.1`).

Probably so (I didn't actually check that yet).
 
> I meant exacly what I wrote, but, yep, in particular, `handler` presence means processing of all routes (including /foo) by this handler.

'/' processes all requests unless there are "more specific" `path`s, e. g. `path = '/foo'`. This applies to all "overlapping" paths (there is a dumb array walk in libh2o, AFAIU).

I still do not understand what exactly do you propose.
Changing existing behavior to "either `handler` or `sites`" is fine with me.
Making "`sites = { { path = '/',  handler = foo},  { path = '/bar', handler = bar } }`" ignore '/bar', process everything with 'foo()' and never use 'bar()' is not. It does not work that way, makes `sites` option useless and #38 impossible to implement (the idea here is to bypass Lua router, it was suggested by @Mons). This is exactly what you are proposing.
 
> Anyway, I see that it is hard to discuss anything without an API description. I propose to describe how things are implemented now (#140) to have a solid ground under feets and return here back.

Ok.

> I had a brief discussion with @Mons regarding all those points. The summary is below.
> 
>     1. There were no `sites` in his API proposal. Instead, there is a separate router (#4), which is configured separately and attached into `httpng.cfg{handler = <...>}`. The API of the router is to be discussed.

This has nothing to do with the Lua-level router, it is libh2o level. We need that for #38 and (maybe) #37.

>     2. It seems, we barely unable to discuss the API of the module, because nobody knows current API (sorry, but that's so). The priority of #140 is very high so. I moved it to Q2. It is more valuable than, say, static file serving. After #140 all changes that relevant to the API must update the API documentation.

Ok.

>     3. If you have thoughts or a proposal about static file serving API, please, share it.

Something like `sites = { { path = '/big_files', handler = '/mnt/big' }, { path = '/', handler = default_handler }  }` (string vs function) or `sites = { { path = '/big_files', static_files = '/mnt/big' }, { path = '/', handler = default_handler }  }`. There would be not "global" handler in that case as you are proposing (and I believe it is inconvenient for a sysadmin to change syntax from "global" handler to `sites` with '/' just to add static file hosting). 

> From me: We should agree how to discuss the API before it'll appear in `master`. Current process ('just push it') was okay for first several months of development, but I hope we'll finish this early stage of development soon and we'll have first early adopters soon.

Ok.

> I can propose several options:
> 
>     1. Discuss API in the relevant issues.
> 
>     2. Enable discussions for this repository and raise questions there.
> 
>     3. Review API in a PR together with an implementation (those PRs will require a review so; the downside here is possibility that the implementation should be rewritten after the API discussion, so I don't recommend this way).
> 
> 
> Any option is okay for me. Please, choose one or propose another way.

I propose creating and discussing API draft (issues or discussions - whatever you prefer), then adjusting it during actual development and finally reviewing in PR. In my experience detailed look at features/existing code/real-world usage helps make API easier to use and implement.

**Comment by Totktonada** [comment]
I would stop diving into `sites` details now, because it's future is unclear. Personally I doubt that we should repeat the router functionality twice in different APIs, but I would elaborate the final decision within our working group (you, me and @Mons).

I left several notes in the relevant issue to don't forget to think around them:

* https://github.com/tarantool/httpng/issues/4#issuecomment-848998027
* https://github.com/tarantool/httpng/issues/38#issuecomment-848998251

----

Generally I would raise an API discussion within an issue, when we don't expect a long discussion, however I would do so in GitHub discussions, when a broad communication is expected. So a user, which doesn't interested in a transient state of the API, will only see a summary in the issue / PR.

**Pull request merged**
